### PR TITLE
Final working Version

### PR DESCRIPTION
**Pull request by globaltoken**
I have tested this Version, and it worked for me, solving all errors we received before.

### CODE REVIEW

**Comment by jeong760** [comment]
@globaltoken, Thank you again. Problem ahs gone home..

**Comment by RepoBike** [comment]
@globaltoken 

I would to add to my pool.  Do you have token info?

**Comment by globaltoken** [comment]
@RepoBike which information do you need?

**Comment by RepoBike** [comment]
@globaltoken

links to website and Linux wallet.

**Comment by globaltoken** [comment]
@RepoBike https://globaltoken.org/#downloads

**Comment by RepoBike** [comment]
@globaltoken

Thank you.

**Pull request merged**
